apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tyo1yrvkf-nodejs
  janus-idp.io/tekton: tyo1yrvkf-nodejs
  backstage.io/kubernetes-id: tyo1yrvkf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tyo1yrvkf-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
