apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tyo1yrvkf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tyo1yrvkf-nodejs 
  name: tyo1yrvkf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tyo1yrvkf-nodejs 
